User:
  Username: "MyUsername"
  Name: "John"
  Surname: "Wick"
  Birthday: "1964-09-12"
  Operative_System: "Windows XP"
  Position: "Data Engineer"
  Company: "Ruska Roma"
  IDE: "vim"
Languages:
  Programming:
    - "Python"
  Other:  # Unused
    - "Bash"
  Real:   # Unused
    - "English"
    - "Russian"

Activities:
  Software:
    - "Embedded"
    - "GUI (Qt)"
    - "ML/AI"
  Hardware: # Unused
    - "Embedded"
    - "RTOS"
    - "PCB"
  Other:    # Unused
    - "Swimming"
    - "Gardening"

Contact:
  Personal_Mail: "john@wick.com"
  Web: https://johnwick.com
  Work_Mail: "wick@ruska.com"
  Linkedin: "https://linkedin.com/in/..."
