User:
  Username: "ItsShunya"
  Name: "Victor"
  Surname: "Luque"
  Birthday: "1998-05-26"
  Operative_System: "NixOS"
  Position: "Embedded Software Engineer"
  Company: "INBRAIN Neuroelectronics"
  IDE: "VSCode"
Languages:
  Programming:
    - "C"
    - "C++"
    - "Python"
  Other:
    - "Bash"
    - "SQL"
    - "LaTeX"
  Real:
    - "English"
    - "Spanish"
    - "Catalan"

Activities:
  Software:
    - "OSS"
    - "Kernel"
    - "OS"
  Hardware:
    - "Embedded"
    - "RTOS"
    - "PCB"
  Other:
    - "Swimming"
    - "Gardening"

Contact:
  Personal_Mail: "luque.viictor@gmail.com"
  Web: https://shunya.is-a.dev
  Work_Mail: "vluque@inbrain-neuroelectronics.com"
  Linkedin: "https://linkedin.com/in/victorluquemartinez"
  Discord: "ItsShunya#1234"
